name: Code Quality Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v2

      # Python einrichten
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # pre-commit installieren
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # pre-commit ausführen
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
