name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v2

      # Python einrichten
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Tests ausführen
      - name: Run tests
        run: |
          pytest
